version: "3"
services:
  develop:
    build: .
    ports:
      - "3000:3000"
    container_name: gfw-user-api-develop
    env_file:
      - dev.env
    environment:
      MONGO_PORT_27017_TCP_ADDR: mongo
    command: develop
    links:
      - mongo
    volumes:
      - ./app:/opt/gfw-user-api/app

  mongo:
    image: mongo:3.4
    container_name: gfw-user-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - mongo_user_vol:/data/db
    restart: always

volumes:
  mongo_user_vol:
networks:
  default:
    external:
      name: control-tower_controltower
